добавил модуль подачи обьявления.
htmlacademy-javascript/482875-keksobooking-23 pull request #6
Opened 2021-06-27 14:56 UTC by davidbars

в главном модуле можно регулировать кол-во выведенных рандомных обьявлений

2021-06-28 10:58 UTC, iv-ov requested changes

2021-06-28 10:58 UTC, iv-ov commented on js/create-cards.js
> +  const imgesFragment = document.createDocumentFragment();
опечатка imges

2021-06-28 10:58 UTC, iv-ov commented on js/create-cards.js
> +    const imageTemplate = photoWrapper.querySelector('.popup__photo');
это лучше до цикла, 1 раз.

2021-06-28 10:58 UTC, iv-ov commented on js/create-cards.js
> +  photoWrapper.children[0].remove();
Неожидаемый побочный эффект. Заем это здесь? Когда вызываешь функцию "get images" не ожидаешь, что из-за этого что-то где-то удалится. Хорошо, когда функция делает что-то одно, какую-то понятную ограниченную задачу. (Не всегда так получается, бывают конечно какие-то связующие функции, которые вызывают другие функции и таким образом делают несколько дел, но это другой случай)

2021-06-28 10:58 UTC, iv-ov commented on js/create-cards.js
> +  features.innerHTML = '';
аналогично как выше, лишнее. Пусть функция просто вернёт набор DOM-узлов, и не занимается удалением чего-либо на странице.

2021-06-28 10:58 UTC, iv-ov commented on js/create-cards.js
> +  } else if (roomsCount > 1 && roomsCount <= 4) {
Если уверены, что больше 20 комнат никогда не будет, то сойдёт.
А более универсальная формула — гуглить со фразой "plural forms", Формы исчисляемого существительного / "Формы множественного числа"

Вот отличный ресурс для переводчиков, там таблица для разных языков, третий столбец — это формула (на псевдо-коде).
http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html

2021-06-28 10:58 UTC, iv-ov commented on js/create-cards.js
> +const popup = newPopupTemplate.cloneNode(true);
Эти строки отработают 1 раз при импорте модуля. А нужно для каждого создания объявления. То есть тоже внутри функции надо

2021-06-28 10:58 UTC, iv-ov commented on js/create-cards.js
> +    title.textContent = cardData.offer.title;
создавать эти title и др переменные внутри здесь стоит.

Проверь при множественных вызовах, последующие будут перезатирвать предыдущие ведь, при текущей реализации.

2021-06-28 10:58 UTC, iv-ov commented on js/create-cards.js
> +    price.innerHTML = `${cardData.offer.price  }<span> ₽/ночь</span>`;
Для надёжности, стоит превращать price в число (или заменять все символы кроме цифр и точек/запятых). Вставка HTML — опасная шутка

2021-06-28 10:58 UTC, iv-ov commented on js/main.js
> +const similarOffers = new Array(1).fill(null).map(() => createOffer());
Добавь лучше несколько, чтобы видеть, что работает правильно

2021-06-28 19:33 UTC, davidbars commented on js/create-cards.js
> +  const imgesFragment = document.createDocumentFragment();
+ поменял на imgsFragment

2021-06-28 19:42 UTC, davidbars commented on js/create-cards.js
> +    const imageTemplate = photoWrapper.querySelector('.popup__photo');
+ вынес за цикл

2021-06-29 07:21 UTC, davidbars commented on js/create-cards.js
> +  features.innerHTML = '';
+

2021-06-29 22:11 UTC, iv-ov approved these changes

2021-06-29 22:11 UTC, merged